name: SpacePortal
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_rotation: ^1.0.0
  auto_size_text: ^2.1.0
  cache_image: ^1.0.5
  cached_network_image: ^2.2.0+1
  cloud_firestore: ^0.13.7
  cupertino_icons: ^1.0.2
  flare_flutter: ^2.0.5
  flutter_riverpod: ^0.13.1
  flutter_svg: ^0.19.1
  google_fonts: ^1.1.0
  http: ^0.12.1
  image: ^2.1.14
  # provider: ^4.3.1
  url_launcher: ^6.0.2
  youtube_explode_dart: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/
    - assets/svgs/
